export DOTFILE_NAME=macos-home

source $HOME/dotfiles/macos/base.zsh

getIp() {
    export PROXY_SOCKS5="socks5://127.0.0.1:7891"
    export PROXY_HTTP="http://127.0.0.1:7891"
}

alias luamake="~/0Workspace/github.com/actboy168/luamake/luamake"
