tap "homebrew/bundle"
# Development kit for the Java programming language
brew "openjdk"
# Tool for reverse engineering 3rd party, closed, binary Android apps
brew "apktool"
# Standalone version of arguments parsing functions from GLIBC
brew "argp-standalone"
# Download with resuming and segmented downloading
brew "aria2"
# Terminal bandwidth utilization tool
brew "bandwhich"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Powerful, enterprise-ready, open source web server with automatic HTTPS
brew "caddy"
# Cross-platform make
brew "cmake"
# Modern, maintained replacement for ls
brew "eza"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl2"
# Small git utilities
brew "git-extras"
# Git extension for versioning large files
brew "git-lfs"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Dex to Java decompiler
brew "jadx"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Next-gen compiler infrastructure
brew "llvm"
# NCurses Disk Usage
brew "ncdu"
# Small build system for use with gyp or CMake
brew "ninja"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Modern replacement for ps written in Rust
brew "procs"
# Easily download, build, install, upgrade, and uninstall Python packages
brew "python-setuptools"
# Display and control your Android device
brew "scrcpy"
# Library for loading images as SDL surfaces and textures
brew "sdl2_image"
# Sample multi-channel audio mixer library
brew "sdl2_mixer"
# Library for using TrueType fonts in SDL applications
brew "sdl2_ttf"
# Prometheus SLO generator
brew "sloth-cli", link: false
# Program that allows you to count code, quickly
brew "tokei"
# Version manager with support for Java, Node.js, Flutter, .NET & more
brew "vfox"
# Internet file retriever
brew "wget"
# Best command-line tool to install and switch between multiple versions of Xcode
brew "xcodes", link: false
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Android SDK component
cask "android-platform-tools"
# Inspect application bundles
cask "apparency"
# Display management tool
cask "betterdisplay"
cask "font-cascadia-code"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-maple-mono"
cask "font-maple-mono-nf-cn"
cask "font-meslo-lg"
cask "font-meslo-lg-nerd-font"
# Free and open-source media player
cask "iina"
# Hex editor for reverse engineers
cask "imhex"
# File archiver
cask "keka"
# Customise mouse behavior
cask "linearmouse"
# System and utility switches
cask "only-switch"
# Replacement for Docker Desktop
cask "orbstack"
# Toolbox companion for QMK Firmware
cask "qmk-toolbox"
# Displays all open files and sockets in use by all running processes
cask "sloth"
# Install and switch between multiple versions of Xcode
cask "xcodes-app"
