source $HOME/dotfiles/macos/base.zsh

alias an="cd ~/0Ant"

bk() {
    cp ~/.zshrc ~/dotfiles/macos/zshrc
    cp ~/.vimrc ~/dotfiles/macos/vimrc
    brew bundle dump --describe --force --brews --casks --taps --mas --no-upgrade --file="~/dotfiles/macos/Brewfile"
}
