git config --global url "git@github.com:".insteadOf "https://github.com/"
git config --global pull.rebase "true"
git config --global alias.s "status"
git config --global alias.sb "status -sb"
git config --global alias.d "diff"
git config --global alias.co "checkout"
git config --global alias.cpk "cherry-pick"
git config --global alias.br "branch"
git config --global alias.last "log -1 HEAD"
git config --global alias.cane "commit --amend --no-edit"
git config --global alias.pr "pull --rebase"
git config --global alias.lo "log --oneline -n 10"
git config --global alias.a "add ."
git config --global alias.cm "commit -m"
git config --global alias.cam "commit --amend -m"
git config --global alias.rh "reset --hard"
git config --global alias.f "fetch"
git config --global alias.fo "fetch origin"
git config --global alias.up "upstream"
git config --global alias.upstream "\!git push -u origin HEAD"
git config --global alias.wt "worktree"
git config --global alias.gt "describe --abbrev=0"
git config --global alias.psuh "push"
git config --global alias.rhh "reset --hard HEAD^"
git config --global alias.rsh "reset --soft HEAD^"
git config --global alias.fm "\!f() { git fetch origin \$1 && git merge origin/\$1; }; f"
git config --global alias.coo "\!f() { git fetch origin \$1 && git checkout \$1; }; f"
git config --global core.excludesfile "~/.gitignore_global"
git config --global core.autocrlf "false"
git config --global core.filemode "false"
git config --global core.quotepath "false"
git config --global core.longpaths "true"
git config --global core.trustctime "false"
git config --global core.attributesfile "~/.attributes_global"
git config --global core.ignorecase "true"
git config --global core.untrackedcache "true"
git config --global color.ui "true"
git config --global init.defaultBranch "main"
git config --global http.postBuffer "655360000"
git config --global diff "text".textconv "cat"
git config --global mergetool.keepBackup "false"
git config --global lfs.concurrenttransfers "16"
git config --global lfs.fetchrecentrefsdays "0"
git config --global lfs.pruneoffsetdays "0"
git config --global lfs.dialtimeout "3"
git config --global lfs.tlstimeout "3"
git config --global lfs "transfer".maxretries "1"
git config --global lfs "transfer".maxretrydelay "2"
git config --global merge "lfs-text".driver "git lfs merge-driver --ancestor %O --current %A --other %B --marker-size %L --output %A --program 'git merge-file --stdout --marker-size=%%L %%A %%O %%B >%%D'"
git config --global rebase.backend "merge"
git config --global rebase.autoSquash "true"
git config --global rebase.autoStash "true"
git config --global rebase.updateRefs "true"
git config --global protocol.version "1"
git config --global safe.directory "*"
git config --global filter "lfs".clean "git-lfs clean -- %f"
git config --global filter "lfs".smudge "git-lfs smudge -- %f"
git config --global filter "lfs".process "git-lfs filter-process"
git config --global filter "lfs".required "true"
git config --global help.autocorrect "prompt"
git config --global column.ui "auto"
git config --global branch.sort "-committerdate"
git config --global tag.sort "version:refname"
git config --global diff.algorithm "histogram"
git config --global diff.colorMoved "plain"
git config --global diff.mnemonicPrefix "true"
git config --global diff.renames "true"
git config --global push.default "simple"
git config --global push.autoSetupRemote "true"
git config --global push.followTags "true"
git config --global fetch.prune "true"
git config --global fetch.pruneTags "true"
git config --global fetch.all "true"
git config --global commit.verbose "true"
git config --global rerere.enabled "true"
git config --global rerere.autoupdate "true"
