git config --global pull.rebase "true"
git config --global alias.s "status"
git config --global alias.sb "status -sb"
git config --global alias.d "diff"
git config --global alias.co "checkout"
git config --global alias.cpk "cherry-pick"
git config --global alias.br "branch"
git config --global alias.last "log -1 HEAD"
git config --global alias.cane "commit --amend --no-edit"
git config --global alias.pr "pull --rebase"
git config --global alias.lo "log --oneline -n 10"
git config --global alias.a "add ."
git config --global alias.cm "commit -m"
git config --global alias.cam "commit --amend -m"
git config --global alias.rh "reset --hard"
git config --global alias.f "fetch"
git config --global alias.up "upstream"
git config --global alias.upstream "!git push -u origin HEAD"
git config --global alias.wt "worktree"
git config --global alias.gt "describe --abbrev=0"
git config --global alias.psuh "push"
git config --global alias.rhh "reset --hard HEAD^"
git config --global alias.rsh "reset --soft HEAD^"
git config --global core.excludesfile "~/.gitignore_global"
git config --global core.autocrlf "false"
git config --global core.filemode "false"
git config --global color.ui "true"
